name: Build Template
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: pwd
      - run: ls
      - run: echo $(pwd)
      - run: echo $(ls)
      - run: cd content
      - name: Run dotnet pack
        run: dotnet pack
      
